In [1]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
from fastai.imports import *

In [3]:
# This file contains all the main external libs we'll use
import fastai
from fastai.imports import *
from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *
from fastai.metrics import *
import pandas as pd
import numpy as np
import shutil
from IPython.display import FileLink, FileLinks

from sklearn.model_selection import train_test_split
import helper
import pyt

In [4]:
#PATH = "/home/nidhin/data/iceberg/"
PATH = os.path.expanduser("~/data/iceberg/")

In [5]:
!ls -l {PATH}

total 1975664
drwxrwxr-x  6 nidhin nidhin       4096 Jan 14 01:19 composites
drwxrwxr-x  2 nidhin nidhin       4096 Jan 21 15:51 models
-rw-rw-r--  1 nidhin nidhin     117951 Oct 23 17:27 sample_submission.csv
-rw-rw-r--  1 nidhin nidhin      38566 Jan  7 20:28 sample_submission.csv.7z
drwxrwxr-x  4 nidhin nidhin       4096 Jan 21 04:12 sub
drwxrwxr-x  2 nidhin nidhin       4096 Jan 21 02:25 test
-rw-rw-r--  1 nidhin nidhin      75819 Jan 21 02:25 test.csv
drwxrwxr-x  2 nidhin nidhin     286720 Jan 21 02:26 test-jpeg
-rw-rw-r--  1 nidhin nidhin 1521771850 Oct 23 17:27 test.json
-rw-rw-r--  1 nidhin nidhin  257127394 Jan  7 20:28 test.json.7z
drwxrwxr-x 16 nidhin nidhin       4096 Jan 21 02:35 tmp
drwxrwxr-x  4 nidhin nidhin       4096 Jan 21 02:25 train
-rw-rw-r--  1 nidhin nidhin      21714 Jan 21 02:25 train.csv
drwxrwxr-x  4 nidhin nidhin      61440 Jan 21 02:25 train-jpeg
-rw-rw-r--  1 nidhin nidhin  196313674 Oct 23 17:23 train.json
-rw-rw-r--  1 nidhin nidhin   44932785 Jan  7 20

In [6]:
seed = 0
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

In [7]:
train_df = pd.read_json(PATH+"/train.json")[["id","inc_angle","is_iceberg"]]

In [8]:
train_df.head()

id inc_angle  is_iceberg
0  dfd5f913   43.9239           0
1  e25388fd   38.1562           0
2  58b2aaa0   45.2859           1
3  4cfc3a18   43.8306           0
4  271f93f4   35.6256           0

In [9]:
#total number of images
num_images = len(train_df) 
sz=64   #image size
bs=32    #batch size
lr=0.001
lrs = [lr/9, lr/3, lr]
f_model = resnet34

In [12]:
def get_ensemble(nmodels):
    models = list()
    
    for i in range(nmodels):
        print(f'-----Training model: {i+1}--------')
        val_idx = get_cv_idxs(num_images, val_pct=0.1, seed=12345) #use 10% of train data as val data
        
        epochs = 5
        cycle_len = 1 
        cycle_mult = 2
        
        
        data = get_data_ens(64, i, val_idx)
        learn = ConvLearner.pretrained(f_model, data,precompute = False, ps=0.55)
        print('training for 64x64')
        learn.fit(lr, epochs, cycle_len=cycle_len, cycle_mult=cycle_mult)
        learn.unfreeze()
        learn.fit(lrs, epochs, cycle_len=cycle_len, cycle_mult=cycle_mult)
        
        print('training for 128x128')
        learn.set_data(get_data_ens(128, i, val_idx))
        learn.freeze()
        learn.fit(lr, epochs, cycle_len=cycle_len, cycle_mult=cycle_mult)
        learn.unfreeze()
        learn.fit(lrs, epochs, cycle_len=cycle_len, cycle_mult=cycle_mult)
        
        print('training for 150x150')
        learn.set_data(get_data_ens(150, i, val_idx))
        learn.freeze()
        learn.fit(lr, epochs, cycle_len=cycle_len, cycle_mult=cycle_mult)
        learn.unfreeze()
        learn.fit(lrs, epochs, cycle_len=cycle_len, cycle_mult=cycle_mult)
        
        print('training for 256x256')
        learn.set_data(get_data_ens(256, i, val_idx))
        learn.freeze()
        learn.fit(lr, epochs, cycle_len=cycle_len, cycle_mult=cycle_mult)
        learn.unfreeze()
        learn.fit(lrs, epochs, cycle_len=cycle_len, cycle_mult=cycle_mult)
        
        
        print('training for 128x128')
        learn.set_data(get_data_ens(128, i, val_idx))
        learn.freeze()
        learn.fit(lr, epochs, cycle_len=cycle_len, cycle_mult=cycle_mult)
        learn.unfreeze()
        learn.fit(lrs, epochs, cycle_len=cycle_len, cycle_mult=cycle_mult)
        
        
        print('training for 64x64')
        learn.set_data(get_data_ens(64, i, val_idx))
        learn.freeze()
        learn.fit(lr, epochs, cycle_len=cycle_len, cycle_mult=cycle_mult)
        learn.unfreeze()
        learn.fit(lrs, epochs, cycle_len=cycle_len, cycle_mult=cycle_mult)
        
        
        learn.save(f'ensem_model_{i}.weights')
        np.savez_compressed(f'{PATH}models/ensem_model_{i}_validx', val_idx=val_idx)
        models.append(learn)
        print(f'-----Training of model {i+1} complete----')
    return models
        
    
def get_data_ens(img_sz, model_index, val_idx):
    
    data = ImageClassifierData.from_csv(PATH,'train-jpeg', f'{PATH}train.csv',
                                     bs=bs, tfms=get_transform(model_index, img_sz),
                                     suffix='.jpeg',
                                     val_idxs=val_idx, test_name='test-jpeg')
    
    return  data

    
    
def get_transform(index, img_sz):
    f_model=resnet34
    index = (index%5)
    print(f'get_transform--{index}: {img_sz}')
    tfms = [
        tfms_from_model(f_model, img_sz, aug_tfms=transforms_basic, max_zoom=1.05),
        tfms_from_model(f_model, img_sz, aug_tfms=transforms_side_on, max_zoom=1.05),
        tfms_from_model(f_model, img_sz, aug_tfms=transforms_top_down, max_zoom=1.05),
        tfms_from_model(f_model, img_sz, aug_tfms=transforms_top_down, max_zoom=1.1),
        tfms_from_model(f_model, img_sz, aug_tfms=transforms_top_down, max_zoom=1.05, crop_type=CropType.RANDOM)]
    return tfms[index]

In [13]:
%time ens = get_ensemble(2)


-----Training model: 1--------
get_transform--0: 64
training for 64x64


HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.80446  0.62024  0.65   ]                      
[ 1.       0.69591  0.55519  0.725  ]                      
[ 2.       0.62873  0.5542   0.7    ]                      
[ 3.       0.57813  0.52206  0.75   ]                      
[ 4.       0.52864  0.50555  0.76875]                      
[ 5.       0.519    0.50788  0.75625]                      
[ 6.       0.4991   0.50587  0.7375 ]                      
[ 7.       0.51109  0.50756  0.74375]                      
[ 8.       0.5266   0.48767  0.76875]                      
[ 9.       0.49111  0.48641  0.775  ]                      
[ 10.        0.47775   0.48524   0.76875]                  
[ 11.        0.47592   0.48064   0.76875]                  
[ 12.        0.48273   0.48317   0.78125]                  
[ 13.        0.47794   0.48123   0.775  ]                  
[ 14.        0.4817    0.48109   0.78125]                  
[ 15.        0.46853   0.48154   0.76875]                  
[ 16.        0.4774    0.47748   0.76875

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.71789  0.61816  0.64375]                      
[ 1.       0.62471  0.56994  0.70625]                      
[ 2.       0.56309  0.59803  0.65   ]                      
[ 3.       0.52356  0.51399  0.71875]                      
[ 4.       0.5055   0.5104   0.73125]                      
[ 5.       0.46003  0.49457  0.74375]                      
[ 6.       0.43084  0.49627  0.725  ]                      
[ 7.       0.43655  0.47357  0.7375 ]                      
[ 8.       0.42243  0.47493  0.73125]                      
[ 9.       0.40967  0.47378  0.75   ]                      
[ 10.        0.3616    0.49732   0.75   ]                  
[ 11.        0.36336   0.47701   0.74375]                  
[ 12.        0.34211   0.46204   0.7625 ]                  
[ 13.        0.35842   0.47783   0.75   ]                  
[ 14.        0.3402    0.43759   0.7625 ]                  
[ 15.        0.3229    0.49234   0.75625]                  
[ 16.        0.31616   0.45741   0.7625 

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.51584  0.63846  0.63125]                      
[ 1.       0.50166  0.55571  0.7    ]                      
[ 2.       0.47883  0.56267  0.6875 ]                      
[ 3.       0.46327  0.54062  0.69375]                      
[ 4.       0.49677  0.52713  0.725  ]                      
[ 5.       0.48531  0.52601  0.73125]                      
[ 6.       0.48206  0.5183   0.74375]                      
[ 7.       0.47261  0.51146  0.74375]                      
[ 8.       0.46145  0.52073  0.71875]                      
[ 9.       0.46058  0.50809  0.7375 ]                      
[ 10.        0.45832   0.50709   0.73125]                  
[ 11.        0.46416   0.53814   0.725  ]                  
[ 12.        0.45515   0.51666   0.7125 ]                  
[ 13.        0.46066   0.50777   0.73125]                  
[ 14.        0.46718   0.52471   0.70625]                  
[ 15.        0.44917   0.49806   0.75625]                  
[ 16.        0.44284   0.50994   0.725  

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.42062  0.43272  0.7875 ]                      
[ 1.       0.39537  0.41975  0.8125 ]                      
[ 2.       0.34805  0.42342  0.825  ]                      
[ 3.       0.31995  0.40879  0.81875]                      
[ 4.       0.30585  0.40627  0.81875]                      
[ 5.       0.27835  0.41103  0.83125]                      
[ 6.       0.29238  0.38433  0.83125]                      
[ 7.       0.27933  0.43983  0.825  ]                      
[ 8.       0.26329  0.39285  0.84375]                      
[ 9.       0.29408  0.36794  0.85   ]                      
[ 10.        0.24468   0.38968   0.8375 ]                  
[ 11.        0.23069   0.37779   0.8375 ]                  
[ 12.        0.20362   0.44371   0.81875]                  
[ 13.        0.19955   0.41396   0.84375]                  
[ 14.        0.20096   0.38961   0.83125]                  
[ 15.        0.23549   0.39161   0.85   ]                  
[ 16.        0.21014   0.35608   0.85   

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.24006  0.43244  0.81875]                      
[ 1.       0.23618  0.41466  0.83125]                      
[ 2.       0.26136  0.42052  0.825  ]                      
[ 3.       0.24708  0.3935   0.83125]                      
[ 4.       0.24279  0.38373  0.84375]                      
[ 5.       0.23581  0.37131  0.83125]                      
[ 6.       0.22656  0.38396  0.84375]                      
[ 7.       0.24698  0.36239  0.825  ]                      
[ 8.       0.25366  0.37422  0.85   ]                      
[ 9.       0.23815  0.35843  0.8375 ]                      
[ 10.        0.23324   0.35803   0.85   ]                  
[ 11.        0.23428   0.35866   0.85   ]                  
[ 12.        0.22547   0.38662   0.8375 ]                  
[ 13.        0.2124    0.36464   0.85625]                  
[ 14.        0.25605   0.38108   0.85   ]                  
[ 15.        0.22973   0.36638   0.85625]                  
[ 16.        0.23988   0.35157   0.825  

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.2733   0.38853  0.85   ]                      
[ 1.       0.22284  0.34217  0.84375]                      
[ 2.       0.20933  0.32941  0.86875]                      
[ 3.       0.19395  0.36861  0.85625]                      
[ 4.       0.16501  0.34402  0.85625]                      
[ 5.       0.15274  0.33093  0.86875]                      
[ 6.       0.1703   0.3561   0.86875]                      
[ 7.       0.14797  0.38839  0.86875]                      
[ 8.       0.13674  0.40046  0.88125]                      
[ 9.       0.13733  0.38462  0.875  ]                      
[ 10.        0.13096   0.38875   0.86875]                  
[ 11.        0.10962   0.4019    0.85   ]                  
[ 12.        0.10647   0.44754   0.85625]                  
[ 13.        0.11576   0.40661   0.86875]                   
[ 14.        0.09524   0.40433   0.85625]                   
[ 15.        0.09426   0.36944   0.86875]                   
[ 16.        0.08368   0.39343   0.86

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.77414  0.68878  0.75625]                      
[ 1.       0.58942  0.51619  0.775  ]                      
[ 2.       0.52961  0.49881  0.775  ]                      
[ 3.       0.46719  0.45168  0.7875 ]                      
[ 4.       0.42822  0.44503  0.78125]                      
[ 5.       0.40972  0.45903  0.775  ]                      
[ 6.       0.41379  0.44556  0.78125]                      
[ 7.       0.40454  0.43459  0.78125]                      
[ 8.       0.40202  0.4536   0.78125]                      
[ 9.       0.3928   0.44627  0.775  ]                      
[ 10.        0.39062   0.43563   0.7875 ]                  
[ 11.        0.37361   0.44024   0.78125]                  
[ 12.        0.38084   0.44983   0.775  ]                  
[ 13.        0.37663   0.4378    0.78125]                  
[ 14.        0.37205   0.43612   0.76875]                  
[ 15.        0.37606   0.42803   0.7875 ]                  
[ 16.        0.37873   0.42496   0.8    

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.32183  0.36031  0.85   ]                      
[ 1.       0.31329  0.33399  0.85625]                      
[ 2.       0.26524  0.33714  0.875  ]                      
[ 3.       0.2541   0.31085  0.875  ]                      
[ 4.       0.23127  0.31252  0.89375]                      
[ 5.       0.21699  0.33483  0.89375]                      
[ 6.       0.22775  0.35735  0.88125]                      
[ 7.       0.20674  0.30982  0.88125]                      
[ 8.       0.18071  0.32052  0.89375]                      
[ 9.       0.16667  0.32587  0.89375]                      
[ 10.        0.15712   0.28709   0.9125 ]                  
[ 11.        0.13058   0.30739   0.90625]                  
[ 12.        0.12953   0.30198   0.90625]                  
[ 13.        0.14172   0.30408   0.90625]                  
[ 14.        0.11412   0.30088   0.9125 ]                  
[ 15.        0.11245   0.32468   0.9125 ]                  
[ 16.        0.10718   0.35668   0.9125 

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.36314  0.49812  0.7875 ]                      
[ 1.       0.31799  0.41108  0.8125 ]                      
[ 2.       0.33754  0.40627  0.8125 ]                      
[ 3.       0.31611  0.37604  0.83125]                      
[ 4.       0.28134  0.36444  0.81875]                      
[ 5.       0.27491  0.36632  0.81875]                      
[ 6.       0.2649   0.35779  0.83125]                      
[ 7.       0.26502  0.3579   0.8375 ]                      
[ 8.       0.24499  0.36029  0.83125]                      
[ 9.       0.24338  0.36497  0.825  ]                      
[ 10.        0.23206   0.3628    0.83125]                  
[ 11.       0.2688   0.3598   0.8375]                      
[ 12.        0.25862   0.3562    0.8375 ]                  
[ 13.        0.25157   0.36216   0.8375 ]                  
[ 14.        0.24461   0.36062   0.8375 ]                  
[ 15.        0.24887   0.3594    0.825  ]                  
[ 16.        0.23446   0.35101   0.8375 

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.13625  0.33245  0.83125]                      
[ 1.       0.11291  0.40075  0.85   ]                      
[ 2.       0.11135  0.39588  0.84375]                       
[ 3.       0.1251   0.44614  0.825  ]                      
[ 4.       0.09583  0.41752  0.85   ]                       
[ 5.       0.09727  0.45404  0.83125]                       
[ 6.       0.0834   0.45233  0.8375 ]                       
[ 7.       0.09092  0.44774  0.825  ]                       
[ 8.       0.07095  0.46174  0.8375 ]                       
[ 9.       0.09922  0.52996  0.825  ]                       
[ 10.        0.09085   0.47209   0.84375]                   
[ 11.        0.10801   0.50294   0.8375 ]                   
[ 12.        0.11871   0.4725    0.84375]                   
[ 13.        0.07741   0.47978   0.83125]                   
[ 14.        0.06217   0.52942   0.83125]                   
[ 15.        0.04734   0.54097   0.825  ]                   
[ 16.        0.07575   0.58

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.37412  0.46651  0.7875 ]                      
[ 1.       0.34268  0.41465  0.8    ]                      
[ 2.       0.35315  0.41012  0.80625]                      
[ 3.       0.35112  0.40262  0.79375]                      
[ 4.       0.32408  0.39075  0.8    ]                      
[ 5.       0.33731  0.38791  0.80625]                      
[ 6.       0.32881  0.3853   0.8125 ]                      
[ 7.       0.31786  0.38917  0.8    ]                      
[ 8.       0.3258   0.39186  0.8    ]                      
[ 9.       0.31159  0.38101  0.8    ]                      
[ 10.        0.30189   0.37896   0.825  ]                  
[ 11.        0.30798   0.37602   0.8125 ]                  
[ 12.        0.30172   0.37682   0.8    ]                  
[ 13.        0.29978   0.37832   0.80625]                  
[ 14.        0.28443   0.37853   0.8125 ]                  
[ 15.        0.31536   0.37537   0.81875]                  
[ 16.        0.31555   0.38109   0.81875

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.26443  0.4128   0.7875 ]                      
[ 1.       0.23656  0.41756  0.8    ]                      
[ 2.       0.20478  0.41905  0.79375]                      
[ 3.       0.2162   0.37467  0.8375 ]                      
[ 4.       0.20124  0.44622  0.83125]                      
[ 5.       0.18254  0.40834  0.81875]                      
[ 6.       0.17662  0.40565  0.83125]                      
[ 7.       0.2195   0.53265  0.78125]                      
[ 8.       0.1959   0.44854  0.83125]                      
[ 9.       0.18975  0.44861  0.825  ]                      
[ 10.        0.15511   0.44984   0.83125]                  
[ 11.        0.14303   0.49287   0.80625]                  
[ 12.        0.13425   0.4593    0.825  ]                  
[ 13.        0.1685    0.43395   0.84375]                  
[ 14.        0.14078   0.46135   0.81875]                  
[ 15.        0.13415   0.48473   0.825  ]                  
[ 16.        0.12735   0.48302   0.81875

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.83909  0.6123   0.65   ]                      
[ 1.       0.69318  0.53653  0.69375]                      
[ 2.       0.62182  0.53234  0.7125 ]                      
[ 3.       0.60567  0.51609  0.71875]                      
[ 4.       0.57521  0.51567  0.725  ]                      
[ 5.       0.57233  0.5129   0.7375 ]                      
[ 6.       0.52891  0.51312  0.7375 ]                      
[ 7.       0.5276   0.50848  0.725  ]                      
[ 8.       0.51831  0.50292  0.7125 ]                      
[ 9.       0.52389  0.49796  0.73125]                      
[ 10.        0.50555   0.49385   0.7375 ]                  
[ 11.        0.50129   0.49014   0.75   ]                  
[ 12.        0.50406   0.49057   0.74375]                  
[ 13.        0.4951    0.49216   0.73125]                  
[ 14.        0.49033   0.48814   0.75625]                  
[ 15.        0.47691   0.48686   0.74375]                  
[ 16.        0.46139   0.48191   0.7625 

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.69331  0.63597  0.64375]                      
[ 1.       0.62369  0.54997  0.69375]                      
[ 2.       0.57037  0.55605  0.675  ]                      
[ 3.       0.54402  0.51929  0.7125 ]                      
[ 4.       0.48928  0.49616  0.71875]                      
[ 5.       0.45787  0.49317  0.7375 ]                      
[ 6.       0.4464   0.49066  0.75   ]                      
[ 7.       0.43907  0.48473  0.75625]                      
[ 8.       0.41915  0.49369  0.76875]                      
[ 9.       0.39037  0.50987  0.75625]                      
[ 10.        0.39294   0.51438   0.75625]                  
[ 11.        0.37915   0.50915   0.7625 ]                  
[ 12.        0.37114   0.49671   0.76875]                  
[ 13.        0.36763   0.50087   0.7625 ]                  
[ 14.        0.38034   0.48365   0.78125]                  
[ 15.        0.38714   0.48862   0.76875]                  
[ 16.        0.36445   0.47905   0.775  

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.50587  0.49186  0.74375]                      
[ 1.       0.52256  0.49588  0.73125]                      
[ 2.       0.50621  0.48439  0.73125]                      
[ 3.       0.48257  0.484    0.74375]                      
[ 4.       0.48128  0.48328  0.73125]                      
[ 5.       0.4583   0.48779  0.73125]                      
[ 6.       0.46716  0.47876  0.74375]                      
[ 7.       0.46163  0.48496  0.73125]                      
[ 8.       0.46688  0.48922  0.73125]                      
[ 9.       0.44783  0.46902  0.7375 ]                      
[ 10.        0.45155   0.47353   0.74375]                  
[ 11.        0.45378   0.48252   0.7375 ]                  
[ 12.        0.45007   0.47878   0.74375]                  
[ 13.        0.45889   0.47659   0.7375 ]                  
[ 14.        0.44913   0.47587   0.73125]                  
[ 15.        0.45489   0.46935   0.75625]                  
[ 16.        0.44888   0.46793   0.74375

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.38425  0.40711  0.76875]                      
[ 1.       0.3673   0.39082  0.80625]                      
[ 2.       0.33861  0.37472  0.8125 ]                      
[ 3.       0.33818  0.36178  0.83125]                      
[ 4.       0.31445  0.35731  0.85   ]                      
[ 5.       0.30437  0.33811  0.85625]                      
[ 6.       0.29274  0.34369  0.8375 ]                      
[ 7.       0.28061  0.36617  0.8375 ]                      
[ 8.       0.26773  0.35452  0.84375]                      
[ 9.       0.27985  0.35065  0.85   ]                      
[ 10.        0.25226   0.33239   0.8375 ]                  
[ 11.        0.23905   0.33168   0.8375 ]                  
[ 12.        0.23244   0.34219   0.85625]                  
[ 13.        0.2715    0.34427   0.85625]                  
[ 14.        0.26163   0.36196   0.85   ]                  
[ 15.        0.27399   0.37809   0.8375 ]                  
[ 16.        0.27592   0.35747   0.88125

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.28066  0.46378  0.83125]                      
[ 1.       0.26971  0.45987  0.83125]                      
[ 2.       0.27575  0.4751   0.8375 ]                      
[ 3.       0.27889  0.43182  0.83125]                      
[ 4.       0.27423  0.4307   0.8375 ]                      
[ 5.       0.27702  0.43316  0.8375 ]                      
[ 6.       0.3085   0.41791  0.8375 ]                      
[ 7.       0.28207  0.41027  0.84375]                      
[ 8.       0.27709  0.40377  0.85   ]                      
[ 9.       0.27343  0.39569  0.83125]                      
[ 10.        0.27535   0.4078    0.84375]                  
[ 11.        0.27121   0.41854   0.8375 ]                  
[ 12.        0.26973   0.39116   0.8375 ]                  
[ 13.        0.27094   0.4066    0.85   ]                  
[ 14.        0.27735   0.40095   0.85   ]                  
[ 15.        0.26763   0.40029   0.85   ]                  
[ 16.        0.25993   0.39712   0.8375 

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.28199  0.38002  0.84375]                      
[ 1.       0.28961  0.38427  0.85625]                      
[ 2.       0.26465  0.35524  0.84375]                      
[ 3.       0.24266  0.35827  0.85   ]                      
[ 4.       0.21457  0.36095  0.84375]                      
[ 5.       0.21146  0.39718  0.8375 ]                      
[ 6.       0.24059  0.37725  0.8375 ]                      
[ 7.       0.22844  0.37907  0.85625]                      
[ 8.       0.2456   0.33252  0.8625 ]                      
[ 9.       0.24989  0.33522  0.86875]                      
[ 10.        0.20913   0.33638   0.875  ]                  
[ 11.        0.20804   0.32192   0.88125]                  
[ 12.        0.19215   0.34875   0.86875]                  
[ 13.        0.18023   0.35781   0.8625 ]                  
[ 14.        0.17951   0.32074   0.88125]                  
[ 15.        0.17803   0.37518   0.85625]                  
[ 16.        0.1694    0.33265   0.8625 

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.43706  0.51746  0.80625]                      
[ 1.       0.43379  0.44488  0.81875]                      
[ 2.       0.41647  0.44742  0.825  ]                      
[ 3.       0.3941   0.42199  0.81875]                      
[ 4.       0.37938  0.4133   0.825  ]                      
[ 5.       0.36302  0.41676  0.8125 ]                      
[ 6.       0.37868  0.41698  0.8125 ]                      
[ 7.       0.38407  0.40931  0.81875]                      
[ 8.       0.36653  0.4142   0.8    ]                      
[ 9.       0.36293  0.40552  0.81875]                      
[ 10.        0.36214   0.41149   0.8    ]                  
[ 11.        0.34487   0.40669   0.8    ]                  
[ 12.        0.36935   0.40903   0.8125 ]                  
[ 13.        0.35622   0.40833   0.80625]                  
[ 14.        0.34027   0.41053   0.80625]                  
[ 15.        0.34563   0.39842   0.825  ]                  
[ 16.        0.34235   0.40487   0.81875

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.2969   0.3445   0.83125]                      
[ 1.       0.29145  0.34041  0.85625]                      
[ 2.       0.2946   0.34484  0.88125]                      
[ 3.       0.28015  0.32047  0.85625]                      
[ 4.       0.24389  0.29688  0.8625 ]                      
[ 5.       0.22524  0.3161   0.85625]                      
[ 6.       0.20764  0.31654  0.88125]                      
[ 7.       0.21682  0.30611  0.8625 ]                      
[ 8.       0.23237  0.332    0.875  ]                      
[ 9.       0.21948  0.28896  0.875  ]                      
[ 10.        0.20519   0.30151   0.8625 ]                  
[ 11.        0.18854   0.30045   0.875  ]                  
[ 12.        0.18227   0.30925   0.88125]                  
[ 13.        0.19183   0.32467   0.86875]                  
[ 14.        0.19724   0.33565   0.86875]                  
[ 15.        0.19359   0.37028   0.84375]                  
[ 16.        0.2053    0.33788   0.84375

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.35285  0.43682  0.79375]                      
[ 1.       0.334    0.375    0.84375]                      
[ 2.       0.3113   0.37163  0.8375 ]                      
[ 3.       0.31301  0.35053  0.84375]                      
[ 4.       0.28539  0.3548   0.85   ]                      
[ 5.       0.30254  0.35791  0.84375]                      
[ 6.       0.33648  0.35048  0.8375 ]                      
[ 7.       0.30357  0.3445   0.84375]                      
[ 8.       0.27785  0.34055  0.84375]                      
[ 9.       0.28977  0.34139  0.84375]                      
[ 10.        0.28609   0.35339   0.8375 ]                  
[ 11.        0.27255   0.33619   0.85   ]                  
[ 12.        0.26801   0.34389   0.84375]                  
[ 13.        0.26669   0.34556   0.83125]                  
[ 14.        0.30623   0.35816   0.85   ]                  
[ 15.        0.27978   0.33726   0.85   ]                  
[ 16.        0.27502   0.33825   0.84375

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.17007  0.27121  0.88125]                      
[ 1.       0.18962  0.3309   0.875  ]                      
[ 2.       0.16065  0.31072  0.88125]                      
[ 3.       0.16965  0.32454  0.88125]                      
[ 4.       0.19334  0.33396  0.86875]                      
[ 5.       0.16443  0.35444  0.86875]                      
[ 6.       0.15414  0.33223  0.86875]                      
[ 7.       0.13642  0.33393  0.875  ]                      
[ 8.       0.1268   0.38838  0.86875]                      
[ 9.       0.12464  0.37841  0.8625 ]                      
[ 10.        0.11373   0.35222   0.8625 ]                  
[ 11.        0.10676   0.41907   0.86875]                  
[ 12.        0.09659   0.41989   0.8625 ]                   
[ 13.        0.14433   0.35926   0.875  ]                   
[ 14.        0.1384    0.37984   0.88125]                  
[ 15.        0.19323   0.35625   0.86875]                  
[ 16.        0.14761   0.33631   0.862

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.41795  0.51942  0.75   ]                      
[ 1.       0.41475  0.4743   0.76875]                      
[ 2.       0.37315  0.46211  0.775  ]                      
[ 3.       0.3752   0.45494  0.775  ]                      
[ 4.       0.36508  0.44717  0.78125]                      
[ 5.       0.35334  0.44548  0.7875 ]                      
[ 6.       0.35609  0.44065  0.7875 ]                      
[ 7.       0.36027  0.45421  0.75625]                      
[ 8.       0.34602  0.44659  0.775  ]                      
[ 9.       0.3435   0.43892  0.7875 ]                      
[ 10.        0.34081   0.43682   0.775  ]                  
[ 11.        0.34312   0.44131   0.775  ]                  
[ 12.        0.32835   0.43405   0.78125]                  
[ 13.        0.3217    0.43461   0.78125]                  
[ 14.        0.33172   0.43896   0.7875 ]                  
[ 15.        0.33734   0.44042   0.775  ]                  
[ 16.        0.3369    0.43582   0.775  

HBox(children=(IntProgress(value=0, description='Epoch', max=31), HTML(value='')))

[ 0.       0.31699  0.3936   0.825  ]                      
[ 1.       0.29619  0.39415  0.80625]                      
[ 2.       0.28503  0.39254  0.825  ]                      
[ 3.       0.27578  0.41126  0.81875]                      
[ 4.       0.2481   0.41863  0.825  ]                      
[ 5.       0.23774  0.40018  0.8125 ]                      
[ 6.       0.2653   0.42866  0.81875]                      
[ 7.       0.25795  0.42617  0.81875]                      
[ 8.       0.26647  0.44682  0.8125 ]                      
[ 9.       0.25729  0.41043  0.8375 ]                      
[ 10.        0.25347   0.46084   0.8    ]                  
[ 11.        0.23265   0.4733    0.8    ]                  
[ 12.        0.2091    0.47028   0.79375]                  
[ 13.        0.20474   0.46489   0.8125 ]                  
[ 14.        0.19741   0.45665   0.81875]                  
[ 15.        0.19869   0.46818   0.80625]                  
[ 16.        0.23317   0.46282   0.81875

# submission

In [14]:
ens

[Sequential(
   (0): Conv2d (3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
   (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True)
   (2): ReLU(inplace)
   (3): MaxPool2d(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), dilation=(1, 1))
   (4): Sequential(
     (0): BasicBlock(
       (conv1): Conv2d (64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
       (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True)
       (relu): ReLU(inplace)
       (conv2): Conv2d (64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
       (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True)
     )
     (1): BasicBlock(
       (conv1): Conv2d (64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
       (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True)
       (relu): ReLU(inplace)
       (conv2): Conv2d (64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
       (bn2): Batc

In [16]:
#Find optimized Threshold
ens_val_probs=list()
#th_list=list()

df2 = pd.DataFrame({'image_name':ens[0].data.test_ds.fnames})
df2.head()

for (idx,mdl) in enumerate(ens):
    test_probs, y=mdl.TTA(is_test=True)
    print(test_probs.shape)
    test_probs = np.mean(np.exp(test_probs),axis=0)

    print(test_probs.shape)

    df2[f'm{idx}'] = test_probs[:,0]
    
    
    #th =opt_th(val_probs, y)
    #th_list.append(val_probs)
    #ens_val_probs.append(val_probs)
#print(th_list)   
#op_th = np.mean(th_list)
#print(op_th)

(5, 8424, 2)                                 
(8424, 2)
(5, 8424, 2)                                 
(8424, 2)


In [17]:
df2.head()

image_name        m0        m1
0  test-jpeg/b2cd6017.jpeg  0.063703  0.337683
1  test-jpeg/f3fa0370.jpeg  0.000710  0.021244
2  test-jpeg/858fd565.jpeg  0.001487  0.004413
3  test-jpeg/9532a83b.jpeg  0.051714  0.125578
4  test-jpeg/6b189724.jpeg  0.006426  0.006195

In [20]:
# set up cutoff threshold for lower and upper bounds, easy to twist 
cutoff_lo = 0.8
cutoff_hi = 0.2

In [21]:
df2['is_iceberg_max'] = df2.iloc[:, 1:3].max(axis=1)
df2['is_iceberg_min'] = df2.iloc[:, 1:3].min(axis=1)
df2['is_iceberg_mean'] = df2.iloc[:, 1:3].mean(axis=1)
df2['is_iceberg_median'] = df2.iloc[:, 1:3].median(axis=1)

In [22]:
df2['is_iceberg_base'] = df2['m0']
df2['is_iceberg'] = np.where(np.all(df2.iloc[:,1:3] > cutoff_lo, axis=1), 
                                    df2['is_iceberg_max'], 
                                    np.where(np.all(df2.iloc[:,1:4] < cutoff_hi, axis=1),
                                             df2['is_iceberg_min'], 
                                             df2['is_iceberg_base']))
df2['is_iceberg'] = np.clip(df2['is_iceberg'].values, 0.001, 0.999)


In [23]:
df2['diff'] = np.abs(df2['is_iceberg'] - df2['m0']) >0.1

In [25]:
df2[['image_name','is_iceberg']].head()

image_name  is_iceberg
0  test-jpeg/b2cd6017.jpeg    0.063703
1  test-jpeg/f3fa0370.jpeg    0.001000
2  test-jpeg/858fd565.jpeg    0.001487
3  test-jpeg/9532a83b.jpeg    0.051714
4  test-jpeg/6b189724.jpeg    0.006195